# Generated by Django 5.1.3 on 2024-12-04 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting_app', '0002_remove_brandsettingmodel_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandsetting',
            name='description',
        ),
        migrations.RemoveField(
            model_name='brandsetting',
            name='price',
        ),
        migrations.RemoveField(
            model_name='brandsetting',
            name='stock',
        ),
    ]
