# Generated by Django 5.1.3 on 2024-12-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting_app', '0004_alter_brand_name_alter_coler_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='factory_model',
            new_name='factory_employee',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='marketing_model',
            new_name='marketing_employee',
        ),
        migrations.AlterField(
            model_name='employee',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
