# Generated by Django 5.1.3 on 2024-12-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting_app', '0008_swaptype'),
    ]

    operations = [
        migrations.CreateModel(
            name='SevenConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_ip', models.GenericIPAddressField(verbose_name='Server IP')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
