# Generated by Django 5.1.3 on 2024-11-25 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300, verbose_name='Full Name')),
                ('accounting_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Accounting Code')),
                ('gspn_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='GSPN ID')),
                ('gspn_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='GSPN Name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=10)),
                ('account_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Account Name')),
                ('email', models.EmailField(blank=True, max_length=300, null=True, verbose_name='Email')),
                ('home_phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Home Phone')),
                ('bussiness_phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bussiness Phone')),
                ('mobile_phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mobile Phone')),
                ('fax', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fax')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('postal_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Postal Code')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
