# Generated by Django 5.1.3 on 2024-11-25 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0003_customer_created_at_customer_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='bussiness_phone',
            new_name='business_phone',
        ),
    ]
