# Generated by Django 5.1.3 on 2024-12-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0004_rename_bussiness_phone_customer_business_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='accounting_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Accounting Code'),
        ),
    ]
