# Generated by Django 5.1.3 on 2024-12-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='status',
            field=models.IntegerField(choices=[(0, 'close'), (1, 'open'), (-1, 'pending')], default=1),
        ),
    ]
