# Generated by Django 5.1.3 on 2024-12-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0003_alter_agents_agent_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceprice',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='deviceprice',
            name='commercial_model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Commercial Model'),
        ),
        migrations.AlterField(
            model_name='deviceprice',
            name='factory_model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Factory Model'),
        ),
        migrations.AlterField(
            model_name='deviceprice',
            name='inter_price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Inter Price'),
        ),
        migrations.AlterField(
            model_name='deviceprice',
            name='memory',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Memory'),
        ),
        migrations.AlterField(
            model_name='deviceprice',
            name='microtel_price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Microtel Price'),
        ),
        migrations.AlterField(
            model_name='deviceprice',
            name='model_code',
            field=models.CharField(max_length=100, verbose_name='Model Code'),
        ),
    ]
