# Generated by Django 5.1.3 on 2024-12-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0005_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='imei',
            field=models.CharField(default=1111, max_length=100),
            preserve_default=False,
        ),
    ]
