# Generated by Django 5.1.3 on 2024-12-10 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0004_rename_bussiness_phone_customer_business_phone'),
        ('service_app', '0007_device_created_at_device_created_by_and_more'),
        ('setting_app', '0008_swaptype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtype', models.CharField(choices=[(0, 'seven'), (1, 'gspn')])),
                ('job_number', models.CharField(max_length=200)),
                ('invoice_amount', models.CharField(max_length=200)),
                ('customer_statement', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_branch', to='service_app.agents')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_created_by', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_customer', to='customer_app.customer')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_device', to='service_app.device')),
                ('swaptype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_swaptype', to='setting_app.swaptype')),
            ],
        ),
    ]
