# Generated by Django 5.1.3 on 2024-12-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0008_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='jobtype',
            field=models.IntegerField(choices=[(0, 'seven'), (1, 'gspn')]),
        ),
    ]
