# Generated by Django 5.1.3 on 2024-12-11 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0010_case_invoice_date'),
        ('setting_app', '0009_sevenconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='brand_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_brand_model', to='setting_app.brandsetting'),
        ),
    ]
