# Generated by Django 5.1.3 on 2024-12-14 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0013_alter_case_job_number_alter_case_jobtype'),
        ('setting_app', '0010_alter_brand_name_alter_brandsetting_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agents',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='agents',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agents',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='deviceprice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='deviceprice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_price_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deviceprice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='agents',
            name='business_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Business Number'),
        ),
        migrations.AlterField(
            model_name='deviceprice',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deviceprice_color', to='setting_app.color', verbose_name='Color'),
        ),
    ]
