# Generated by Django 5.1.3 on 2024-12-14 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0014_agents_created_at_agents_created_by_and_more'),
        ('setting_app', '0010_alter_brand_name_alter_brandsetting_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceprice',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_price_color', to='setting_app.color', verbose_name='Color'),
        ),
    ]
