# Generated by Django 5.1.3 on 2024-12-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0017_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='%Y-%m-%d'),
        ),
    ]
