# Generated by Django 5.1.3 on 2024-12-18 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0019_paymenttype_refundtype_swap'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paymenttype_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='refundtype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refundtype_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
