# Generated by Django 5.1.3 on 2024-12-18 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0020_alter_paymenttype_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swap',
            old_name='peyment_type',
            new_name='payment_type',
        ),
    ]
