# Generated by Django 5.1.3 on 2024-12-18 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0021_rename_peyment_type_swap_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swap',
            name='financial_approved_at',
        ),
    ]
