# Generated by Django 5.1.3 on 2024-12-22 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0022_remove_swap_financial_approved_at'),
        ('setting_app', '0011_paymentsource_paymenttype_refundtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swap',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swap_payment_type', to='setting_app.paymenttype'),
        ),
        migrations.RemoveField(
            model_name='refundtype',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='swap',
            name='refund_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swap_refund_type', to='setting_app.refundtype'),
        ),
        migrations.AlterField(
            model_name='swap',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_case', to='service_app.case'),
        ),
        migrations.DeleteModel(
            name='PaymentType',
        ),
        migrations.DeleteModel(
            name='RefundType',
        ),
    ]
