# Generated by Django 5.1.3 on 2024-12-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger_app', '0002_alter_loggers_request_alter_loggers_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggers',
            name='view',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
