# Generated by Django 5.1.3 on 2024-12-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0003_alter_account_dep_number_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('0', 'decharge'), ('1', 'charge')]),
        ),
    ]
