# Generated by Django 5.1.3 on 2024-12-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0004_alter_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('decharge', 'decharge'), ('charge', 'charge')]),
        ),
    ]
