# Generated by Django 5.1.3 on 2024-12-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0005_alter_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('charge', 'charge'), ('decharge', 'decharge')], default='charge', max_length=100),
        ),
    ]
