# Generated by Django 5.1.3 on 2024-12-10 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0003_alter_transaction_amount'),
        ('finance_app', '0006_remove_transaction_type_transaction_transaction_type'),
    ]

    operations = [
    ]
