# Generated by Django 5.1.3 on 2024-12-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0009_transaction_updated_status_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='updated_status_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
